FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake libtool pkg-config build-essential autoconf-archive bison flex

ADD . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/link-grammar/.libs
RUN cp /repo/link-parser/.libs/link-parser /repo/link-parser
